name: OpenInv
main: com.lishid.openinv.OpenInv
version: ${openinv.version}
author: lishid
authors: [Jikoo]
description: >
             This plugin allows you to open a player's inventory as a chest and interact with it in real time.
commands:
  openinv:
    aliases: [oi, inv, open]
    description: Open a player's inventory
    permission: OpenInv.*;OpenInv.openinv
    usage: |-
           /<command> [Player] - Open a player's inventory
  openender:
    aliases: [oe]
    description: Opens the enderchest of a player
    permission: OpenInv.*;OpenInv.openender
    usage: |-
           /<command> [Player] - Open a player's enderchest
  searchinv:
    aliases: [si]
    description: Search and list players having a specific item
    permission: OpenInv.*;OpenInv.search
    usage: |-
           /<command> <Item> [MinAmount] - Item can be the ID or the Bukkit Material, MinAmount is the minimum amount required
  silentchest:
    aliases: [sc, silent]
    description: Toggle silent chest function, which hides the animation of a chest when opened or closed, and suppresses the sound.
    permission: OpenInv.*;OpenInv.silent
    usage: |-
           /<command> [Check] - Check or toggle silent chest
  anychest:
    aliases: [ac]
    description: Toggle anychest function, which allows opening of blocked chests.
    permission: OpenInv.*;OpenInv.anychest
    usage: |-
           /<command> [Check] - Checks or toggle anychest
