name: Build

on:
  push:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Install Spigot Dependencies
        run: . scripts/install_spigot_dependencies.sh

      - name: Build With Maven
        run: mvn -e clean package -am -P all

      - name: Upload Distributable Jar
        id: upload-final
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./target/OpenInv.jar
      - name: Upload API Jar
        id: upload-api
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./api/target/openinvapi*.jar
