name: Release to CurseForge

on:
  release:
    types: [ released ]

jobs:
  curseforge_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set CurseForge Variables
        run: . scripts/set_curseforge_env.sh

      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.release.id }}
          file: OpenInv.jar

      - name: Create CurseForge Release
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 31432
          game_endpoint: minecraft
          file_path: ./OpenInv.jar
          changelog: ${{ github.event.release.body }}
          display_name: ${{ github.event.release.name }}
          game_versions: ${{ env.CURSEFORGE_MINECRAFT_VERSIONS }}
          release-type: release
